import { IMAGE_UPLOAD_ALLOWED_MIME_TYPES, IMAGE_UPLOAD_MAX_BYTES } from "../../../shared/constants/uploadLimits";

export const DASHBOARD_SUPPORTED_AVATAR_IMAGE_TYPES = new Set(IMAGE_UPLOAD_ALLOWED_MIME_TYPES);

export const DASHBOARD_AVATAR_MAX_BYTES = IMAGE_UPLOAD_MAX_BYTES;

